version: '3.4'

services:
  resortforecaster.api:
    image: ${DOCKER_REGISTRY-}resortforecasterapi
    build:
      context: .
      dockerfile: ResortForecaster.Api/Dockerfile
  resort-forecaster-db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - SA_PASSWORD=Abcd1234!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"